version: "3"
services:
  dashboardandds:
    build: ./dashboardandds
    image: evolkotest1/react1
    ports:
      - "8000:3000"
    depends_on:
      - nodeproxy
  nodeproxy:
    build: ./nodeproxy
    image: evolkotest1/node1
    ports:
      - "3001:3001"
    depends_on:
      - mongo
    links:
      - mongo
  mongo:
    image: mongo
    ports:
      - "27017:27017"
